#Assignment


In [1]:
#1.Write a NumPy program to get the numpy version and show numpy build configuration. 
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

In [8]:
#2. Write a NumPy program to  get help on the add function.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [14]:
#3. Write a NumPy program to test whether none of the elements of a given array is zero.
#The numpy. all() function tests whether all array elements along the mentioned axis evaluate to True.

a=np.array([12,34,56,78])
b=np.array([34,6,0,34])
print("Original array",a)
print("\nArray contain all non-zero element=",np.all(a))
print("\nOriginal array",b)
print("\nArray contain all non-zero element=",np.all(b))


Original array [12 34 56 78]

Array contain all non-zero element= True

Original array [34  6  0 34]

Array contain all non-zero element= False


In [21]:
#4. Write a NumPy program to test whether any of the elements of a given array is non-zero.
#The any() function in NumPy is used to check if all the elements of an array along a given axis evaluate to True 
a=np.array([12,34,56,78])
b=np.zeros((2,2))
print("Original array",a)
print("Array contain non zero elements=",np.any(a))
print("Original array",b)
print("Array contain non zero elements=",np.any(b))



Original array [12 34 56 78]
Array contain non zero elements= True
Original array [[0. 0.]
 [0. 0.]]
Array contain non zero elements= False


In [24]:
#any and all
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
d=np.array([1,2,5,6])
print("a==d",(a==d).all())
print("a==d",(a==d).any())

a==d False
a==d True


In [34]:
#5.How to extract items that satisfy a given condition from 1D array?
#1. Q. Extract all even numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Even number=",arr[arr%2==0])
#2. Q.Extract all odd numbers from arr
print("Odd Number=",arr[arr%2!=0])

Even number= [0 2 4 6 8]
Odd Number= [1 3 5 7 9]


In [35]:
#6.How to replace items that satisfy a condition with another value in numpy array?
#Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [57]:
#Q. 7 Replace all odd numbers in arr with -1 without changing arr
#where(condition, [x, y])

#Return elements chosen from `x` or `y` depending on `condition`.

arr = np.array([10, 6, 2, 3, 4, 5, 6, 7, 8, 9])
a=np.where([arr%2!=0],-1,arr)
b=np.where(arr<4,1,arr)
print("arr=",arr)
print("a=",a)
print("b=",b)

arr= [10  6  2  3  4  5  6  7  8  9]
a= [[10  6  2 -1  4 -1  6 -1  8 -1]]
b= [10  6  1  1  4  5  6  7  8  9]


In [69]:
#8.How to reshape an array?
#Q. Convert a 1D array to a 2D array with 2 rows
a=np.arange(10)
b=np.reshape(a,(5,2))
print("a=",a)
print("b=",b)

a= [0 1 2 3 4 5 6 7 8 9]
b= [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [98]:
#9.How to stack two arrays vertically?
#Q. Stack arrays a and b vertically
 #a= np.arange(10).reshape(2,-1)
#b = np.repeat(1, 10).reshape(2,-1)

a=np.arange(10)#Return evenly spaced values within a given interval.

b=np.repeat(1,10) #np.repeat(a, repeats, axis=None) 
#Docstring: Repeat elements of an array.here 1 repeated 10 times
print("a=",a)
print("b=",b)
np.concatenate([a,b],axis=0)
print("Output1=",np.vstack((a,b)))
print("output2=",np.concatenate([a,b],axis=0))
print("Reshape",a.reshape(2,-1))

a= [0 1 2 3 4 5 6 7 8 9]
b= [1 1 1 1 1 1 1 1 1 1]
Output1= [[0 1 2 3 4 5 6 7 8 9]
 [1 1 1 1 1 1 1 1 1 1]]
output2= [0 1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1]
Reshape [[0 1 2 3 4]
 [5 6 7 8 9]]


In [111]:
a=np.arange(10).reshape(2,-1)#concatenation axis=1 works for 2d array so convert 1d to 2d
b=np.repeat(1,10) .reshape(2,-1)
print("a=",a)
print("b=",b)
c=np.concatenate((a,b),axis=0)
print("c=",c)
print(np.r_[a,b])


a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [115]:
#10.How to stack two arrays horizontally?
#Q. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

print("a=",a)
print("b=",b)
print("Output1=",np.hstack([a,b]))
print("output2=",np.concatenate([a,b],axis=1))
print("output3=",np.c_[a,b])

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
Output1= [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
output2= [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
output3= [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [121]:
#11.How to generate custom sequences in numpy without hardcoding?
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a
#Input:
#a = np.array([1,2,3])
#output=array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a=np.array([1,2,3])
print("a=",a)
b=np.repeat(a,3)#Repeat elements of an array.
print("b=",b)
c=np.tile(a,3) #Construct an array by repeating A the number of times given by reps.tile(a,reps)
print("C=",c)
d=np.hstack([b,c])
print("d=",d)

a= [1 2 3]
b= [1 1 1 2 2 2 3 3 3]
C= [1 2 3 1 2 3 1 2 3]
d= [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [2]:
#12.How to get the common items between two python numpy arrays?
# Input:
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:
# array([2, 4])

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
c

array([2, 4])

In [6]:
#13.How to remove from one array those items that exist in another?
# Q. From array a remove all items present in array b

# Input:
# a = np.array([1,2,3,4,5])
# b = np.array([5,6,7,8,9])

# Desired Output:
# array([1,2,3,4])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

In [7]:
#14.How to get the positions where elements of two arrays match?
# Q. Get the positions where elements of a and b match

# Input:
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output:
# #> (array([1, 3, 5, 7]),)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(a==b)
c

(array([1, 3, 5, 7], dtype=int64),)

In [15]:
#15. How to extract all numbers between a given range from a numpy array?
# Q. Get all items between 5 and 10 from a.
# Input:
# a = np.array([2, 6, 1, 9, 10, 3, 27])

# Desired Output:
# (array([6, 9, 10]),)

a=np.array([2,6,1,9,10,3,27])
ind=np.where(np.logical_and(a>=5,a<=10))
index=np.where((a>=5) & (a<=10))
#index = np.where((a >= 5) & (a <= 10))
print(ind)
print(index)


(array([1, 3, 4], dtype=int64),)
(array([1, 3, 4], dtype=int64),)


In [32]:
#16. How to make a python function that handles scalars to work on numpy arrays?

# Q. Convert the function maxx that works on two scalars, to work on two arrays.
# Input:
# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)
# #> 5
# Desired Output:

# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)


array([6., 7., 9., 8., 9., 7., 5.])

In [38]:
#17.How to swap two columns in a 2d numpy array?
# Q. Swap columns 1 and 2 in the array arr.

# arr = np.arange(9).reshape(3,3)
# arr
# To Swap Columns in numpy
#arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]

arr = np.arange(9).reshape(3,3)
print("Before Swaping=\n",arr)
arr[:,[1,2]]=arr[:,[2,1]]
print("After Swaping=\n",arr)

# To Swap Rows in numpy
#arr[[start_index, last_index],:] = arr[[last_index, start_index],:]
arr1 = np.arange(9).reshape(3,3)
print("Before Swaping=\n",arr1)
arr1[[1,2],:]=arr1[[2,1],:]
print("After Swaping=\n",arr1)


Before Swaping=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After Swaping=
 [[0 2 1]
 [3 5 4]
 [6 8 7]]
Before Swaping=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After Swaping=
 [[0 1 2]
 [6 7 8]
 [3 4 5]]
